### ISSUE TITLE
Character count - As a user i want to see how much chracters were extracted from my documents as i have a max number of characters upload per plan

### ISSUE THREAD

**Issue by jrouxel** [Prologue-XR/brainbambam#1]
![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/5e255f69-a6f4-4d31-bb63-e88e84348261)

**Comment by FernandoSLuz** [comment]
This is not a Quivr feature, maybe you can find a script here: 

https://www.geeksforgeeks.org/python-program-to-read-character-by-character-from-a-file/

https://github.com/MAR-AM/B

**Comment by jrouxel** [comment]
@FernandoSLuz did you managed to complete this task ?

**Comment by FernandoSLuz** [comment]
> @FernandoSLuz did you managed to complete this task ?

Yes, it's done, we don't have a maximum character limit as it will be linked with the payment plans

**Comment by jrouxel** [comment]
@FernandoSLuz 
Here is the character limit. Let m know if it make sens...

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/3b4a2931-8b4d-47da-ae36-a5de56bfaf4d)
![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/d31c7e2f-5ab5-45e3-b47a-7b900f6f1201)
