### ISSUE TITLE
Feedback and bug reports / As a user, I should be able to report bugs/billing problems and other classic problem issues

### ISSUE THREAD

**Issue by FernandoSLuz** [Prologue-XR/brainbambam#10]
Implement backend services for handling user feedback and bug reports.
- Description: Design and document the feedback and bug report services in the backend.

**Comment by jrouxel** [comment]
@FernandoSLuz i created a contact support button that I implemented in the footer of the design a bot pages and a couple of places in the website. When cliked on, the user should be redirected to this page to report bugs but also report problem on different topics (see below)

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/c59e88f4-45ef-4236-bc15-6ff25913cac0)

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/36488b90-a4ec-42e5-a23a-e222c20d9016)

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/c541e6d6-6216-48f5-8d9f-147e23113859)

Make sure we have these tables in the back-end so we can retrieve these pieces of information and it can be sent as a package to support@prologue.ai
