### ISSUE TITLE
As a developer, I want to automate the deployment process to Kubernetes.

### ISSUE THREAD

**Issue by FernandoSLuz** [Prologue-XR/brainbambam#14]
Finalize CI/CD Pipeline Setup for Kubernetes
Description: Finalize the setup of the CI/CD pipeline for Kubernetes, test, and ensure a smooth automated deployment process. Document this process.

**Comment by FernandoSLuz** [comment]
1st step (and probably one of the longest were solved. so far I've created the automation plan and made it work, alongside with setting the ips as static using load-balance.


[azure_updates.md](https://github.com/Prologue-XR/brainbambam-backend/files/12911115/azure_updates.md)
[metadata_tutorials.md](https://github.com/Prologue-XR/brainbambam-backend/files/12911116/metadata_tutorials.md)
[variables.md](https://github.com/Prologue-XR/brainbambam-backend/files/12911117/variables.md)

**Comment by FernandoSLuz** [comment]
![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/51529517/923b96e9-adee-4f3b-a605-7f32816b437d)

**Comment by jrouxel** [comment]
Hey @FernandoSLuz, you have seens this ? https://learn.microsoft.com/en-us/azure/architecture/microservices/ci-cd-kubernetes.

Do you plan using Helm ? https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/helm-deploy-v0?view=azure-pipelines
