### ISSUE TITLE
week 1 **Update Brain CRUD operations**

### ISSUE THREAD

**Issue by jrouxel** [Prologue-XR/brainbambam#15]
As a developer, I want to update the current CRUD operations to include new features for text-to-speech (TTS), automatic speech recognition (ASR), and avatar so that the application remains up-to-date and accessible to users.

Each brain should be able to:

+ have a distinct name (name your brain)
+ it's own system prompt
+  a short description (accessible to public or private sharing)

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/16999148-5215-4b2d-885f-e83d5ee2a028)

+ an open AI key that is hashed if public (enter his own API Key or Prologue key with Pro Plan)
+ use should be able to choose the different accessible models of Open AI (gpt4 or gpt3.5)
+ the temperature
+ the max tokens

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/fea4227b-2de4-425f-a1bb-99486842b278)

+ the text-to-speech (the first iteration should be with Eleven labs) (enter his own API Key or Prologue key with Pro Plan)

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/4e083b5b-7c20-411e-a889-d061a199167c)

+ Automatic Speech Recognition (the first iteration should be with Azure tts)

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/e565d19b-b580-4b7b-bd02-49accaf09510)

+ Avatar service (The first iteration the user should be able to Choose a visual or upload 3D object (gltf))

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/9fc9740f-031a-4ae6-adec-95d37031e27c)

+ Knowledge base: user should be able to upload Text, document, spreadsheet, presentation, audio, video and URLs and see the names of the documents/links he updated.

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/fd1bcc01-0111-47aa-9c35-be84a9cc0d71)

+ Be able to make his brain private or public
+ have it's own sharable link
+ add new users by entering email and roles (viewer/editor/owner)
+ have different embedding modes (standard or pup-up) with embed scripts or iframe for each

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/c2c247c2-f733-42d6-88c9-37feb3fec3be)

+ a distinct QR code so users can share or print them on premice (pretty sure it's only a front-end task but maybe it's linked to back-end for the visual retrieval ? anyway Ronaldo will use this: https://vercel.com/templates/next.js/qrGPT
+ user have a way to delete or change access at all time.

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/593127fe-c55a-4094-b933-152f4ffd8ac3)

**Comment by jrouxel** [comment]
@FernandoSLuz do this way of creating task help or not really worth my time?

**Comment by FernandoSLuz** [comment]
@jrouxel , I've created the tasks already, but I loved the descriptions, I will just focus on the tts and stt before doing it all, or it will become an epic
