### ISSUE TITLE
As a developer, I need to understand the current system to formulate its documentation.

### ISSUE THREAD

**Issue by FernandoSLuz** [Prologue-XR/brainbambam#2]
**### Review existing services and start backend documentation.**
Review and understand the current backend services, their operations, and architecture. Begin developing the comprehensive backend documentation for future use.

**Comment by jrouxel** [comment]
Hey @FernandoSLuz Fernando,

i think this is a good starting point: https://brain.quivr.app/docs/get_started/intro.html

Why not use this as we have 90% in common with Quivr ?

**Comment by FernandoSLuz** [comment]
@jrouxel , I will create docs about what I add only, like kubernets, avatar, tts and stt systems.
This task will update everything during the weeks.

**Comment by jrouxel** [comment]
@FernandoSLuz ok but can we pull the actual Quivr doc and modify it with what we add-on so it's complete?

**Comment by FernandoSLuz** [comment]
the current backend documentation can be found here:
https://github.com/Prologue-XR/brainbambam-backend/tree/develop/prologue-docs

**Comment by jrouxel** [comment]
@FernandoSLuz is it all the doc of our project for back-end ?

**Comment by FernandoSLuz** [comment]
> @FernandoSLuz is it all the doc of our project for back-end ?

These are the docs required to upload to azure kubernetes service
