### ISSUE TITLE
As a user, I want to share my brain including the avatar visual portion

### ISSUE THREAD

**Issue by FernandoSLuz** [Prologue-XR/brainbambam#3]
Update Brain CRUD operations.
- Description: Modify the Brain routes to include the new features and document these changes.

**Comment by FernandoSLuz** [comment]
So far i've made some changes in the backend routes, but I'm still analyzing all the dependant database tables that will feed from that.
I will be able to feed it this week.

**Comment by jrouxel** [comment]
Make sure you follow the design updates and add the tables for these

![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/46896321/749db52f-c704-4d56-9423-c0e88bc78ebc)

**Comment by FernandoSLuz** [comment]
![Image](https://github.com/Prologue-XR/brainbambam-backend/assets/51529517/398d6082-085b-4834-a61a-da19823b644b)

**Comment by jrouxel** [comment]
@FernandoSLuz what is the status on this ?

**Comment by FernandoSLuz** [comment]
Ongoing task, plan to finish it tomorrow.
