### ISSUE TITLE
As a pro user, I should be able to subscribe to pro memberships and update my user information.

### ISSUE THREAD

**Issue by FernandoSLuz** [Prologue-XR/brainbambam#8]
Implement Pro Users Subscription and Update User info feature.
- Description: Implement and document the backend routes and services for the Plus and Pro Users Subscription and Update User info features.

**Comment by jrouxel** [comment]
@FernandoSLuz @ronaldocaldeireirojonson i think this project could help us achieve a good portion of this task for the front-end: https://vercel.com/templates/next.js/tier

we can clone the pricing model from the above links and make it our own. We can sync it with our Stripe "Test Mode" for both our dev and staging environments. We can also push this model to prod as shown in the project, by making use of the Tier CLI using this command where you use the model builder link and set a environment variable called STRIPE_API_KEY which should be a restricted key generated will all permissions in our Stripe live mode.
